#!/usr/bin/env python3
"""Generate STE writing rules from a style profile and install them into a CLAUDE.md.

The block is written between markers so that re-running updates it in place
instead of appending a second copy. Everything outside the markers is left
untouched.

Usage:
    install_rules.py --profile ~/.claude/ste-profile.json --dry-run
    install_rules.py --profile ~/.claude/ste-profile.json --target ~/.claude/CLAUDE.md

Always run --dry-run first and show the output to the user. This writes to a
file the user did not necessarily open, so they need to see it before it lands.
"""
import argparse
import json
import os
import sys

BEGIN = "<!-- BEGIN asd-ste100 -->"
END = "<!-- END asd-ste100 -->"

BASE_RULES = [
    "Use short, common words. Write \"do\" not \"perform\", \"start\" not \"commence\", \"use\" not \"utilize\", \"make sure\" not \"ensure\".",
    "Write \"before\" not \"prior to\", \"after\" not \"subsequent to\", \"to\" not \"in order to\", \"if\" not \"in the event that\".",
    "Give one word one meaning. Do not reach for a synonym to add variety.",
    "Technical Names are always allowed. Never simplify the name of a part, tool, system, or document.",
    "Technical Verbs are always allowed. Keep \"drill\", \"ream\", \"torque\", \"calibrate\".",
    "Do not write \"etc.\", \"e.g.\", \"i.e.\", or \"and/or\". List the items, or write the sentence again.",
    "Use the imperative for instructions.",
    "Use active voice.",
    "Do not use -ing forms. Exception: -ing words inside a Technical Name, such as \"landing gear\".",
    "Use \"must\" for a requirement, \"can\" for ability, \"will\" for the future. Do not use \"shall\", \"should\", \"may\", or \"might\".",
    "Use simple tenses only. Write \"was removed\", not \"has been removed\".",
    "Give one instruction per sentence. Two actions are permitted only when they occur together.",
    "Use a maximum of 3 nouns in a cluster. Break longer clusters with prepositions.",
    "Put the condition first: \"If the pressure is more than 100 psi, open the valve.\"",
    "Use a maximum of 6 sentences in a descriptive paragraph. Put the topic in the first sentence.",
    "Use WARNING for a risk of injury, CAUTION for a risk of damage to equipment, NOTE for information only.",
    "Start a warning with a command, then give the reason: \"DO NOT TOUCH THE VALVE. THE VALVE IS HOT.\"",
    "Do not put a procedural step inside a note.",
]


def profile_rules(p):
    """Return the four profile-driven rules, in document order."""
    out = []

    if p.get("articles", "keep") == "keep":
        out.append(("articles", 'Keep the articles. Write "Remove the bolt", not "Remove bolt". Do not use sentence fragments.'))
    else:
        out.append(("articles", 'Drop articles and allow fragments. Write "Remove bolt". This overrides STE rule S-4.'))

    lim = p.get("sentence_limit", {})
    proc = lim.get("procedural", 20)
    desc = lim.get("descriptive", 25)
    if proc == desc:
        s = f"Keep sentences to {proc} words or less."
    else:
        s = f"Keep procedural sentences to {proc} words or less, and descriptive sentences to {desc} words or less."
    if lim.get("carve_out"):
        s += " Root-cause, security, and technical guidance may go over when a split would lose meaning. Flag the overrun."
    out.append(("sentence_limit", s))

    if p.get("lists", "ste") == "ste":
        out.append(("lists", "Use numbers for sequential steps only. Use letters or dashes for items with no order."))
    else:
        out.append(("lists", "Number every list, sequential or not, so that items are easy to reference. This overrides STE rule X-1."))

    if p.get("warning_placement", "before") == "before":
        out.append(("warnings", "Put warnings and cautions before the step they apply to. Put notes after the related text."))
    else:
        out.append(("warnings", "Put the action first, then the warning. This overrides STE rule C-2."))

    return out


def build_block(p):
    name = p.get("profile", "custom")
    overrides = [k for k, _ in profile_rules(p)]
    rules = BASE_RULES + [text for _, text in profile_rules(p)]

    lines = [
        BEGIN,
        "# Technical Writing — ASD-STE100",
        "",
        f"Profile: {name}. Generated by the asd-ste100 skill. Edit the profile, not this block.",
        "",
        "Apply these rules to technical documentation: procedures, manuals, warnings, work cards, and maintenance steps. Do not apply them to chat replies or informal messages.",
        "",
    ]
    for i, r in enumerate(rules, 1):
        lines.append(f"{i}. {r}")

    lines += [
        "",
        "To check a document against these rules, run the asd-ste100 skill.",
        "",
        "ASD-STE100 and Simplified Technical English are trademarks of ASD, Brussels. These rules are a summary written for this tool, not the specification. This is an unofficial aid and certifies nothing. The specification is free from asd-ste100.org.",
        END,
    ]
    if name != "strict":
        lines.insert(-2, "This profile deliberately overrides some STE rules, so its output is STE-derived rather than STE.")
        lines.insert(-2, "")
    return "\n".join(lines) + "\n"


def resolve_target(raw):
    """Only ever write a file called CLAUDE.md.

    The skill passes a fixed path, so this is not reachable in normal use. It
    exists because the script is also a standalone write primitive, and one
    that will create directories and write anywhere is worth constraining
    before something else learns to call it.
    """
    # realpath, not abspath: abspath leaves symlinks unresolved, and open()
    # follows them — a link named CLAUDE.md would pass the check and write
    # through to whatever it points at. Resolve first, then check.
    target = os.path.realpath(os.path.expanduser(raw))
    if os.path.basename(target) != "CLAUDE.md":
        sys.exit(f"refusing: --target must name a CLAUDE.md file, got {target}")
    return target


def install(block, target):
    existing = ""
    if os.path.exists(target):
        with open(target, encoding="utf-8") as f:
            existing = f.read()

    if BEGIN in existing and END in existing:
        head = existing.split(BEGIN)[0]
        tail = existing.split(END, 1)[1]
        new = head.rstrip("\n") + "\n\n" + block + tail.lstrip("\n")
        action = "updated existing block in"
    elif existing.strip():
        new = existing.rstrip("\n") + "\n\n" + block
        action = "appended block to"
    else:
        new = block
        action = "created"

    os.makedirs(os.path.dirname(os.path.abspath(target)), exist_ok=True)
    with open(target, "w", encoding="utf-8") as f:
        f.write(new)
    return action


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", required=True, help="Path to ste-profile.json")
    ap.add_argument("--target", help="CLAUDE.md to write. Required unless --dry-run.")
    ap.add_argument("--dry-run", action="store_true", help="Print the block, write nothing.")
    args = ap.parse_args()

    with open(args.profile, encoding="utf-8") as f:
        p = json.load(f)

    block = build_block(p)

    if args.dry_run or not args.target:
        print(block, end="")
        if not args.target:
            print("\n(dry run: pass --target to install)", file=sys.stderr)
        return

    target = resolve_target(args.target)
    action = install(block, target)
    print(f"{action} {target}")
    print(f"Block is delimited by {BEGIN} / {END}. Delete those lines and everything between to remove it.")


if __name__ == "__main__":
    sys.exit(main())
